version: '3.8'

services:
  defender:
    build: ./defender
    container_name: defender
    tty: true
    volumes:
      - ./defender:/app
      - ./logs/suricata:/var/log/suricata:ro
    networks:
      - testbed-net
    depends_on:
      - ids
    command: python main.py

  ids:
    image: jasonish/suricata:latest-amd64
    container_name: ids
    networks:
      testbed-net:
        ipv4_address: 172.20.0.10 # Static IP
    volumes:
      - ./ids-config/suricata.yaml:/etc/suricata/suricata.yaml
      - ./logs/suricata:/var/log/suricata
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    command: >
      bash -c "suricata-update -q &&
               suricata -i eth0 -c /etc/suricata/suricata.yaml --runmode=workers"

  traffic-replay:
    build: ./traffic-replay
    container_name: traffic-replay
    networks:
      - testbed-net
    cap_add:
      - NET_RAW # Needed by Scapy to craft raw packets
    depends_on:
      - ids

networks:
  testbed-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
